env:
  - GO111MODULE=on
  - DOCKER_CLI_EXPERIMENTAL="enabled"
builds:
  - binary: inventory
    main: ./
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - -s -w
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
dockers:
  - dockerfile: Dockerfile
    use: buildx
    goarch: amd64
    goos: linux
    build_flag_templates:
      - --pull
      - --platform=linux/x86_64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url={{.GitURL}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    image_templates:
      - 'ghcr.io/ovrclk/{{ .ProjectName }}:{{ .ShortCommit }}-amd64'
      - 'ghcr.io/ovrclk/{{ .ProjectName }}:{{ .Version }}-amd64'
      - 'ghcr.io/ovrclk/{{ .ProjectName }}:latest-amd64'
  - dockerfile: Dockerfile
    use: buildx
    goarch: arm64
    goos: linux
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url={{.GitURL}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    image_templates:
      - 'ghcr.io/ovrclk/{{ .ProjectName }}:{{ .ShortCommit }}-arm64'
      - 'ghcr.io/ovrclk/{{ .ProjectName }}:{{ .Version }}-arm64'
      - 'ghcr.io/ovrclk/{{ .ProjectName }}:latest-arm64'
docker_manifests:
  - name_template: ghcr.io/ovrclk/{{ .ProjectName }}:{{ .ShortCommit }}
    image_templates:
      - ghcr.io/ovrclk/{{ .ProjectName }}:{{ .ShortCommit }}-amd64
      - ghcr.io/ovrclk/{{ .ProjectName }}:{{ .ShortCommit }}-arm64
  - name_template: ghcr.io/ovrclk/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/ovrclk/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/ovrclk/{{ .ProjectName }}:{{ .Version }}-arm64
  - name_template: ghcr.io/ovrclk/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/ovrclk/{{ .ProjectName }}:latest-amd64
      - ghcr.io/ovrclk/{{ .ProjectName }}:latest-arm64
