name: Release
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .makerc
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Go mod tidy
        run: |
          go mod tidy
      - name: Gen changelog
        run: |
          make changelog
        env:
          GORELEASER_TAG: "${{ env.RELEASE_VERSION }}"
      - if: startsWith(github.ref,'refs/tags/v')
        name: Release dry-run
        run: make release-dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
      - if: startsWith(github.ref,'refs/tags/v')
        name: setup release environment
        run: |-
          echo '${{secrets.GHCR_USER}}:${{secrets.GHCR_TOKEN}}:ghcr.io' > .docker-creds
          echo 'DOCKER_CREDS_FILE=.docker-creds' > .release-env
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' >> .release-env
      - if: startsWith(github.ref,'refs/tags/v')
        name: Release
        run: |-
          sudo rm -rf dist
          make release
